### ISSUE TITLE
Uppgift 02 - 08 - Feedback

### ISSUE THREAD

**Issue by pellekofot** [WilliamCBrodd/webb2-01#3]
Uppgift 02. OK. CSS rad 20 **span:last-of-type** behövs inte
Uppgift 03. OK.
Uppgift 04. OK. Jag hade löst den med **font-variant: small-caps;**
Uppgift 05. OK.
Uppgift 06. OK.
Uppgift 07. OK. Du har en onödig radbrytning på rad 21.
Uppgift 08. Du har fel på rad 17 i CSS:en, **font-size: 3rems;** ska vara **font-size: 3rem;**

**Comment by WilliamCBrodd** [comment]
Inga problem
